# Generated by Django 5.0 on 2023-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userprofile_social_userprofile_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social',
            field=models.ManyToManyField(to='api.social'),
        ),
    ]
